<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="OpenMcdf" />
    <PackageReference Include="SharpCompress" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WinMatsch.Analysis\WinMatsch.Analysis.csproj" />
    <ProjectReference Include="..\..\src\WinMatsch.Core\WinMatsch.Core.csproj" />
  </ItemGroup>

</Project>
