using WinMatsch.Core;

namespace WinMatsch.Rules.Policy;

/// <summary>
/// PIPE-2: pins every manifest of the run — version, installer, default locale, and each extra
/// locale — to the single source-of-truth manifest schema version
/// (<see cref="ManifestVersion.Default"/>, currently 1.12.0). Manifests created or modified at
/// an older ManifestVersion are upgraded in place; the <c>$schema</c> header comment is
/// regenerated by the serializer from the same constant, so field and comment cannot drift.
/// When the caller supplies raw header-comment observations
/// (<see cref="PolicyEvidence.SchemaHeaderComments"/>), a header that does not name the pinned
/// version produces a finding — raw emitted-file validation itself stays in WinMatsch.Validation.
/// </summary>
public sealed class Pipe2ManifestVersionPinRule : IRule
{
    private readonly PolicyEvidence _evidence;

    public Pipe2ManifestVersionPinRule(PolicyEvidence? evidence = null)
    {
        _evidence = evidence ?? PolicyEvidence.Empty;
    }

    public string Id => RuleCatalogueIds.Pipe2;

    public RuleCategory Category => RuleCategory.Policy;

    public RuleSeverity Severity => RuleSeverity.Warning;

    public string Description => "Pins all manifests to the single source-of-truth manifest schema version.";

    public void Apply(ManifestContext context)
    {
        ArgumentNullException.ThrowIfNull(context);

        PackageManifests manifests = context.Manifests;
        ManifestVersion target = ManifestVersion.Default;

        Pin(context, manifests.Version.ManifestVersion, v => manifests.Version.ManifestVersion = v, target, "Version");
        Pin(context, manifests.Installer.ManifestVersion, v => manifests.Installer.ManifestVersion = v, target, "Installer");
        Pin(context, manifests.DefaultLocale.ManifestVersion, v => manifests.DefaultLocale.ManifestVersion = v, target, "DefaultLocale");
        for (int i = 0; i < manifests.Locales.Count; i++)
        {
            LocaleManifest locale = manifests.Locales[i];
            Pin(context, locale.ManifestVersion, v => locale.ManifestVersion = v, target, $"Locales[{i}]");
        }

        CheckSuppliedHeaders(context, target);
    }

    private void Pin(
        ManifestContext context,
        ManifestVersion current,
        Action<ManifestVersion> set,
        ManifestVersion target,
        string documentName)
    {
        if (current == target)
        {
            return;
        }

        set(target);
        context.AddTrace(this,
            $"{documentName}: upgraded ManifestVersion {current} to the pinned {target}; the $schema comment is regenerated from the same constant on write.");
    }

    private void CheckSuppliedHeaders(ManifestContext context, ManifestVersion target)
    {
        foreach ((string path, string header) in _evidence.SchemaHeaderComments.OrderBy(static p => p.Key, StringComparer.Ordinal))
        {
            if (!header.Contains(target.Value, StringComparison.Ordinal))
            {
                context.AddFinding(this, RuleSeverity.Warning,
                    $"The observed $schema header comment does not reference the pinned manifest version {target.Value}; regenerate the file through the serializer. Raw emitted-file checks are owned by validation.",
                    path);
            }
        }
    }
}
