<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BinMatch.Downloads\BinMatch.Downloads.csproj" />
    <ProjectReference Include="..\BinMatch.Downloads.LockHost\BinMatch.Downloads.LockHost.csproj" />
  </ItemGroup>

</Project>
